config/routes.rb
Rails.application.routes.draw do
  resources :exams, param: :slug
  resources :exam_types, param: :slug

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'exam_types#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
  validates :year, presence: true, uniqueness: {scope: :exam_type_id}
  validates :price, allow_nil: true, numericality: {only_integer: true}

  belongs_to :exam_type

  def to_param
    slug
  end

  def price
    self[:price].nil? ? exam_type.price : self[:price] unless new_record?
  end

  def open_at
    self[:open_at].strftime("%d-%m-%Y at %H:%M")
  end

end

app/models/exam_type.rb
class ExamType < ApplicationRecord
  validates :label, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {only_integer: true}

  has_many :exams

  def to_param
    slug
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exam_types_controller.rb
class ExamTypesController < ApplicationController
  before_action :set_exam_type, only: [:show, :edit, :update, :destroy]

  layout 'app'

  # GET /exam_types
  # GET /exam_types.json
  def index
    @exam_types = ExamType.all
  end

  # GET /exam_types/1
  # GET /exam_types/1.json
  def show
  end

  # GET /exam_types/new
  def new
    @exam_type = ExamType.new
  end

  # GET /exam_types/1/edit
  def edit
  end

  # POST /exam_types
  # POST /exam_types.json
  def create
    @exam_type = ExamType.new(exam_type_params)

    respond_to do |format|
      if @exam_type.valid?
        exam_type_with_highest_code = ExamType.order(code: :desc).first
        @exam_type.code = exam_type_with_highest_code.nil? ? 0 : (exam_type_with_highest_code.code.to_i + 1)
        @exam_type.slug = exam_type_slug
        @exam_type.save

        format.html {redirect_to @exam_type, notice: 'Exam type was successfully created.'}
        format.json {render :show, status: :created, location: @exam_type}
      else
        format.html {render :new}
        format.json {render json: @exam_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /exam_types/1
  # PATCH/PUT /exam_types/1.json
  def update
    respond_to do |format|
      if @exam_type.valid?
        attributes = exam_type_params
        attributes[:slug] = exam_type_slug
        @exam_type.update(attributes)

        format.html {redirect_to @exam_type, notice: 'Exam type was successfully updated.'}
        format.json {render :show, status: :ok, location: @exam_type}
      else
        format.html {render :edit}
        format.json {render json: @exam_type.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /exam_types/1
  # DELETE /exam_types/1.json
  def destroy
    @exam_type.destroy
    respond_to do |format|
      format.html {redirect_to exam_types_url, notice: 'Exam type was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exam_type
    @exam_type = ExamType.find_by_slug(params[:slug])
  end

  # Return Exam Type slug.
  def exam_type_slug
    "#{params[:exam_type][:label]} #{DateTime.current.to_i}".parameterize
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exam_type_params
    params.require(:exam_type).permit(:label, :price)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[show edit update destroy]
  after_action :send_notifications, only: :create

  layout 'app'

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    @exam_type = ExamType.find(params[:exam][:exam_type_id])
    if @exam_type.nil?
      render :new
    else
      @exam.exam_type = @exam_type
    end

    respond_to do |format|
      if @exam.valid?
        @exam.slug = exam_slug
        @exam.save

        SendSmsJob.perform_later @exam

        format.html {redirect_to @exam, notice: 'Exam was successfully created.'}
        format.json {render :show, status: :created, location: @exam}
      else
        format.html {render :new}
        format.json {render json: @exam.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    @exam_type = ExamType.find(params[:exam][:exam_type_id])
    if @exam_type.nil?
      render :new
    else
      @exam.exam_type = @exam_type
    end

    respond_to do |format|
      if @exam.update(exam_params)
        attributes = exam_params
        attributes[:slug] = exam_slug
        @exam.update(attributes)

        format.html {redirect_to @exam, notice: 'Exam was successfully updated.'}
        format.json {render :show, status: :ok, location: @exam}
      else
        format.html {render :edit}
        format.json {render json: @exam.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html {redirect_to exams_url, notice: 'Exam was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exam
    @exam = Exam.find_by_slug(params[:slug])
  end

  def exam_slug
    "#{@exam_type.label} #{params[:exam][:year]} #{DateTime.current.to_i}".parameterize
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exam_params
    params.require(:exam).permit(:year, :price, :open_at, :is_current, :activated)
  end

  def send_notifications
    SendSmsWorker.perform_async @exam.id

    ExamMailer.exam_registered(@exam.id).deliver_later
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_types_helper.rb
module ExamTypesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exam_types/_form.html.haml
= form_with(model: exam_type, local: true, class: "ui form #{exam_type.errors.any? ? "error" : nil }") do |form|
  - if exam_type.errors.any?
    %div{class: "ui error message"}
      %ul{class: "list"}
        - exam_type.errors.full_messages.each do |message|
          %li= message

  %div{:class => [:field, "#{exam_type.errors[:label].any? ? "error" : nil }"]}
    = form.label :label
    = form.text_field :label, require: true

  %div{:class => [:field, "#{exam_type.errors[:price].any? ? "error" : nil }"]}
    = form.label :price
    = form.number_field :price

  = form.submit :submit, class: "ui button"

app/views/exam_types/edit.html.haml
%h2{class: "ui header", style: "text-align: center"} Edit Exam Type

= render 'form', exam_type: @exam_type

app/views/exam_types/index.html.haml
%h2{class: "ui header", style: "text-align: center"} Exam Types

= link_to 'New Exam Type', new_exam_type_path, {class: "ui primary button"}

%table{class: "ui celled table"}
  %thead
    %tr
      %th Label
      %th Price
      %th Actions

  %tbody
  - @exam_types.each do |exam_type|
    %tr
      %td= exam_type.label
      %td= exam_type.price
      %td
        = link_to raw('<i class="unhide icon"></i>'), exam_type, {class: "ui icon button", "data-tooltip": "Show", "data-position": "top center"}
        = link_to raw('<i class="edit icon"></i>'), edit_exam_type_path(exam_type), {class: "ui icon yellow button", "data-tooltip": "Edit", "data-position": "top center"}
        = link_to raw('<i class="trash icon"></i>'), exam_type, {class: "ui icon red button", "data-tooltip": "Edit", "data-position": "top center", method: :delete, "data-confirm": "Are you sure you want to delete #{exam_type.label} ?"}

app/views/exam_types/new.html.haml
%h2{class: "ui header", style: "text-align: center"} New Exam Type

= render 'form', exam_type: @exam_type

app/views/exam_types/show.html.haml
%h2{class: "ui header", style: "text-align: center"} Show Exam Type

- if notice
  #div{class: "ui green floating message", style: "text-align: center"}
    = notice

%p
  %strong
    Label:
  = @exam_type.label

%p
  %strong
    Price:
  = @exam_type.price

= link_to 'Edit', edit_exam_type_path(@exam_type), {class: "ui yellow button"}

app/views/exams/_form.html.haml
= form_with(model: exam, local: true, class: "ui form #{exam.errors.any? ? "error" : nil }") do |form|

  - if exam.errors.any?
    %div{class: "ui error message"}
      %ul{class: "list"}
        - exam.errors.full_messages.each do |message|
          %li= message

  %div{:class => ["field", "#{exam.errors[:exam_type].any? ? "error" : nil }"]}
    = form.label :exam_type
    = form.collection_select(:exam_type_id, ExamType.all, :id, :label, {}, {class: "ui search dropdown"})

  %div{:class => [:field, "#{exam.errors[:year].any? ? "error" : nil }"]}
    = form.label :year
    = form.number_field :year

  %div{:class => [:field, "#{exam.errors[:price].any? ? "error" : nil }"]}
    = form.label :price
    = form.number_field :price

  %div{:class => [:field, "#{exam.errors[:open_at].any? ? "error" : nil }"]}
    = form.label :open_at
    = text_field_tag 'exam[open_at]', "#{exam.new_record? ? "#{DateTime.current.strftime("%d-%m-%Y at %H:%M")}" : exam.open_at}"

  %div{:class => ['field', "#{exam.errors[:activated].any? ? "error" : nil }"]}
    %div{class: 'ui checkbox'}
      = form.check_box :activated
      = form.label :activated

  %div{:class => ['field', "#{exam.errors[:is_current].any? ? "error" : nil }"]}
    %div{class: 'ui checkbox'}
      = form.check_box :is_current
      = form.label :is_current

  = form.submit :submit, class: "ui button"

- content_for :script do
  :javascript
    $('.ui.checkbox').checkbox();
    $('.ui.dropdown').dropdown();
    flatpickr("#exam_open_at", { enableTime: true, dateFormat: "d-m-Y at H:i" });

app/views/exams/edit.html.haml
%h2{class: "ui header", style: "text-align: center"} Edit Exam

= render 'form', exam: @exam

app/views/exams/index.html.haml
%h2{class: "ui header", style: "text-align: center"} Exams

= link_to 'New Exam', new_exam_path, {class: "ui primary button"}

%table{class: "ui celled table"}
  %thead
    %tr
      %th Label
      %th Price
      %th Open at
      %th Activated
      %th Is current
      %th Actions

  %tbody
  - @exams.each do |exam|
    %tr
      %td= "#{exam.exam_type.label} #{exam.year}"
      %td= exam.price
      %td= exam.open_at
      %td
        %i{class: "#{exam.activated ? "green check" : "red remove"} circle outline big icon"}
      %td
        %i{class: "#{exam.is_current ? "green check" : "red remove"} circle outline big icon"}
      %td
        = link_to raw('<i class="unhide icon"></i>'), exam, {class: "ui icon button", "data-tooltip": "Show", "data-position": "top center"}
        = link_to raw('<i class="edit icon"></i>'), edit_exam_path(exam), {class: "ui icon yellow button", "data-tooltip": "Edit", "data-position": "top center"}
        = link_to raw('<i class="trash icon"></i>'), exam, {class: "ui icon red button", "data-tooltip": "Edit", "data-position": "top center", method: :delete, "data-confirm": "Are you sure you want to delete #{exam.exam_type.label} #{exam.year} ?"}

app/views/exams/new.html.haml
%h2{class: "ui header", style: "text-align: center"} New Exam

= render 'form', exam: @exam

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @exam.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @exam.price %>
</p>

<p>
  <strong>Open at:</strong>
  <%= @exam.open_at %>
</p>

<p>
  <strong>Is current:</strong>
  <%= @exam.is_current %>
</p>

<p>
  <strong>Activated:</strong>
  <%= @exam.activated %>
</p>

<p>
  <strong>Exam type:</strong>
  <%= @exam.exam_type.label %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/layouts/app.html.haml
!!! 5
%html
  %head
    %title Ruby Exam
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application'

  %body
    %h3{class: "ui block header"}
      !eiXam

    %div{class: "ui grid container"}
      %div{class: "three wide column"}
        %div{class: "ui secondary vertical pointing menu"}
          = link_to "Exam Types", exam_types_path, class: "item #{ current_page?(controller: :exam_types, action: :index) ? "active": nil }"

          = link_to "Exams", exams_path, class: "item #{ current_page?(controller: :exams, action: :index) ? "active": nil }"

      %div{class: "thirteen wide column"}
        %div{class: "ui grey raised stacked segment"}
          = yield

    = javascript_include_tag 'application'
    = yield :script

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyMysql</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>